INTENT2IDX = {"greeting": 0,
              "req_start": 1,
              "req_temperature": 2,
              "thank": 3,
              "req_instruction": 4,
              "confirm": 5,
              "req_repeat": 6,
              "negate": 7,
              "req_amount": 8,
              "req_parallel_action": 9,
              "req_ingredient": 10,
              "req_use_all": 11,
              "other": 12,
              "req_is_recipe_finished": 13,
              "req_tool": 14,
              "req_duration": 15,
              "affirm": 16,
              "req_is_recipe_ongoing": 17,
              "req_title": 18,
              "req_ingredient_list": 19,
              "goodbye": 20,
              "req_ingredient_list_length": 21,
              "req_ingredient_list_ends": 22,
              "req_substitute": 23}

INTENTS = ["greeting",
           "req_start",
           "req_temperature",
           "thank",
           "req_instruction",
           "confirm",
           "req_repeat",
           "negate",
           "req_amount",
           "req_parallel_action",
           "req_ingredient",
           "req_use_all",
           "other",
           "req_is_recipe_finished",
           "req_tool",
           "req_duration",
           "affirm",
           "req_is_recipe_ongoing",
           "req_title",
           "req_ingredient_list",
           "goodbye",
           "req_ingredient_list_length",
           "req_ingredient_list_ends",
           "req_substitute"]

INTENT_DESCRIPTIONS = {
    "greeting": "greeting",
    "req_start": "ask to start the instruction",
    "req_temperature": "ask about the cooking temperature",
    "thank": "thank",
    "req_instruction": "ask for the instruction",
    "confirm": "confirm the current stage",
    "req_repeat": "ask to repeat the last information",
    "negate": "negate",
    "req_amount": "ask about the amount information",
    "req_parallel_action": "ask for actions which can be done in parallel",
    "req_ingredient": 'ask about the ingredient',
    "req_use_all": "ask whether can use all",
    "other": "other intent",
    "req_is_recipe_finished": "ask whether the recipe is finished",
    "req_tool": "ask about the cooking tool",
    "req_duration": "ask about cooking duration",
    "affirm": "affirm",
    "req_is_recipe_ongoing": 'ask whether there are any steps left to do',
    "req_title": "ask for the title",
    "req_ingredient_list": "list the ingredients",
    "goodbye": "goodbye",
    "req_ingredient_list_length": "ask about the amount of ingredient",
    "req_ingredient_list_ends": "ask whether this is all ingredient",
    "req_substitute": "ask for tool or ingredient substitutions"
}

INTENT_DESCRIPTIONS2 = {
    "greeting": "greet to start a conversation",
    "req_start": "ask to start the instruction",
    "req_temperature": "request the exact temperature expression for an action",
    "thank": "express gratitude",
    "req_instruction": "request the next instruction after having confirmed accomplishment of previous instructions",
    "confirm": "establish the fact that one or several actions have been accomplished",
    "req_repeat": "ask for repeating a mentioned entity or instruction",
    "negate": "give a negative statement",
    "req_amount": "ask for the exact quantity of an entity",
    "req_parallel_action": "ask for actions which can be done in parallel",
    "req_ingredient": 'ask for the next ingredient',
    "req_use_all": "want to know if a specific ingredient shall be used up",
    "other": "other intent",
    "req_is_recipe_finished": "ask if the cooking process ends or not",
    "req_tool": "request a specific tool entity",
    "req_duration": "request the time needed for an action",
    "affirm": "give a positive statement",
    "req_is_recipe_ongoing": 'ask if there are more steps to follow',
    "req_title": "ask for the recipe title",
    "req_ingredient_list": "request a detailed list of ingredients before the instruction part starts",
    "goodbye": "express good wishes at the end of a conversation",
    "req_ingredient_list_length": "request the total number of ingredients",
    "req_ingredient_list_ends": "want to know if all the ingredients have been introduced",
    "req_substitute": "want to know if it is possible to use an alternative ingredient instead of the prescribed one"
}
